# Project information
site_name:   Phylogenies.jl
site_description: Phylogenetic Trees for julia.
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/Phylogenies.jl/

# Repository
repo_url:  https://github.com/BioJulia/Phylogenies.jl

# Copyright
copyright: Copyright (c) 2016 The BioJulia Organisation

# Documentation and theme
theme: biojulia
docs_dir: 'build'

# Options
extra:
  logo: images/biojl.png
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
    - Introduction: index.md
    - Phylogenetic Trees: man/phylo.md
    - Contributing: man/contributing.md
